--[[
region skill_targets_data.lua
date: 2015-9-18
time: 16:15:26
author: Nation
]]
g_SkillTargetsData = {
    [1] = { atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, arraytype=0,},
    [2] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [3] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [4] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [5] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [6] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [7] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [8] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [9] = {atype=2, srctype=1, targettype=1, angle=30, sorttype=0, layer=lay_all_role, enemy=true},
    [10] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [11] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true,},
    [12] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [13] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, arraytype=0,},
    [14] = {atype=2, srctype=3, targettype=1, angle=360, radius=2, layer=lay_all_role, enemy=true, position=2},
    [15] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [16] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [17] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [18] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [19] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [20] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [21] = {atype=2, srctype=1, targettype=1, angle=90, layer=lay_all_role, enemy=true},
    [22] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [23] = {atype=2, srctype=1, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true},
    [24] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [25] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [26] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [27] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [28] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [29] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [30] = {atype=2, srctype=1, targettype=1, angle=360, radius=3, layer=lay_all_role, enemy=true, },
    [31] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [32] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [33] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [34] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [35] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [36] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [37] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [38] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [39] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [40] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, includeself=true, layer=lay_all_role, enemy=true},
    [41] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [42] = {atype=2, srctype=1, targettype=1, angle=30, layer=lay_all_role, enemy=true},
    [43] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [44] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [45] = {atype=2, srctype=1, targettype=1, radius=3, angle=360, layer=lay_all_role, enemy=true, },
    [46] = {atype=2, srctype=1, targettype=4, width=1.5, layer=lay_all_role, enemy=true, },
    [47] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    [48] = {atype=2, srctype=1, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true, includeself=false,},
    [49] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    [50] = {atype=2, srctype=1, targettype=1, radius=3.5, angle=360, layer=lay_all_role, enemy=true},
    [51] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [52] = {atype=2, srctype=1, targettype=4, buffid=25, bufflv=5, layer=lay_all_role, enemy=true, },
    [53] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [54] = {atype=2, srctype=3, targettype=1, radius=2, angle=360, position=1, layer=lay_all_role, enemy=true, },
    [55] = {atype=2, srctype=1, targettype=1, radius=5, angle=240, layer=lay_all_role, enemy=true, },
    [56] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [57] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    [58] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [59] = {atype=2, srctype=1, targettype=1, radius=3, angle=240, layer=lay_all_role, enemy=true, },
    [60] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [61] = {atype=2, srctype=1, targettype=1, angle=30, layer=lay_all_role, enemy=true},
    [62] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false, includeself=true, sorttype=4, targetcnt=1,},
    [63] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [64] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [65] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    [66] = {atype=2, srctype=1, targettype=1, radius=2.5, targetcnt=3, angle=360, layer=lay_all_role, enemy=true, },
    [67] = {atype=2, srctype=1, targettype=1, radius=2.5, targetcnt=3, angle=120, layer=lay_all_role, enemy=true, },
    [68] = {atype=2, srctype=1, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true, },
    [69] = {atype=2, srctype=5, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true, targetcnt=3, },
    [70] = {atype=2, srctype=5, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true, targetcnt=3, },
    [71] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [72] = {atype=2, srctype=5, targettype=1, radius=2.5, angle=360, layer=lay_all_role, enemy=true, targetcnt=3, },
    [73] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [74] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [75] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [76] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [77] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [78] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [79] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true,},
    [80] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [81] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [82] = {atype=2, srctype=1, targettype=4, aroundradius=1.5, layer=lay_all_role, enemy=true},
    [83] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true },
    [84] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [85] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [86] = {atype=2, srctype=3, targettype=1, radius=2, angle=360, position=2, layer=lay_all_role, enemy=true},
    [87] = {atype=2, srctype=3, targettype=2, radius=2, angle=360, position=3, position_offset=3.7, layer=lay_all_role, enemy=true},
    [88] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [89] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [90] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [91] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [92] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [93] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [94] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [95] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [96] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [97] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [98] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [99] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [100] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [101] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [102] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [103] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [104] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [105] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [106] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [107] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [108] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [109] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [110] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [111] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [112] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [113] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [114] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [115] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [116] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [117] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [118] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role, lengthtype=1},
    [119] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role, arraytype=0},
    [120] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [121] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role,enemy=true},
    [122] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [123] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [124] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [125] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [126] = {atype=2, srctype=5, targettype=1, radius=2.5, angle=360, includeself=true, layer=lay_all_role, enemy=true},
    [127] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [128] = {atype=2, srctype=1, targettype=1, angle=90, layer=lay_all_role, enemy=true},
    [129] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [130] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [131] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [132] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [133] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [134] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [135] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role, },
    [136] = {atype=2, srctype=3, targettype=2, radius=2.5, angle=360, enemy=true, layer=lay_all_role, arraytype=0},
    [137] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [138] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [139] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [140] = {atype=2, srctype=1, targettype=4, width=1.5, layer=lay_all_role, enemy=true},
    [141] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [142] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [143] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    [144] = {atype=2, srctype=5, targettype=1, radius=3, angle=360, layer=lay_all_role, enemy=true, includeself=true},
    [145] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [146] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [147] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [148] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [149] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [150] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [151] = {atype=2, srctype=5, targettype=1, radius=2, angle=360, targetcnt=3, includeself=true, layer=lay_all_role, enemy=true},
    [152] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [153] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [154] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [155] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [156] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [157] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [158] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [159] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [160] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [161] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [162] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [163] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [164] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [165] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [166] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [167] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [168] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [169] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, },
    [170] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [171] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [172] = {atype=2, srctype=2, targettype=3, radius=2.5, angle=360, enemy=true, layer=lay_all_role,},
    [173] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false, includeself=true},
    [174] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [175] = { atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true, arraytype=0,},
    [176] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [177] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [178] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true,},
    [179] = { atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role },--查找目标
    [180] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true,},
    [181] = {atype=2, srctype=1, targettype=4, width=3, layer=lay_all_role, enemy=true, arraytype=0,},
    [182] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false, includeself=true, sorttype=4, radius=0,targetcnt=1,},
    [183] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [184] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [185] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [186] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true },
    [187] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [188] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [189] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [190] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [191] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [192] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [193] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [194] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [195] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [196] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [197] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [198] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [199] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [200] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true },
    [201] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [202] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [203] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [204] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [205] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [206] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false, targetcnt=3, includeself=true},
    [207] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, },
    [208] = { atype=2, srctype=1, targettype=6, angle=360, enemy=false, layer=lay_all_role, includeself=true, },--查找目标
    [209] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [210] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [211] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [212] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [213] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [214] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [215] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [216] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [217] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [218] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [219] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [220] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [221] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [222] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [223] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [224] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [225] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [226] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [227] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [228] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [229] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [230] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [231] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [232] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [233] = {atype=2, srctype=1, targettype=1, angle=120, enemy=true, layer=lay_all_role,},
    [234] = {atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role,},
    [235] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [236] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [237] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [238] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [239] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [240] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [241] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [242] = {atype=2, srctype=1, targettype=4, enemy=true, layer=lay_all_role,},
    [243] = {atype=2, srctype=1, targettype=1, angle=90, layer=lay_all_role, enemy=true},
    [244] = {atype=2, srctype=1, targettype=1, angle=180, layer=lay_all_role, enemy=true},
    [245] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [246] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [247] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [248] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [249] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [250] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [251] = {atype=2, srctype=1, targettype=1, angle=50, layer=lay_all_role, enemy=true},
    [252] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [253] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [254] = { atype=2, srctype=1, targettype=1, angle=360, enemy=true, layer=lay_all_role },
    [255] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [256] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [257] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [258] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [259] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [260] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [261] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [262] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [263] = {atype=2, srctype=1, targettype=1, angle=60, enemy=true, layer=lay_all_role,},
    [264] = {atype=2, srctype=1, targettype=1, angle=60, radius=3.5, enemy=true, layer=lay_all_role,},
    [265] = {atype=2, srctype=1, targettype=1, angle=120, radius=5, enemy=true, layer=lay_all_role,},
    [266] = {atype=2, srctype=1, targettype=4, width=1.5, length=5, enemy=true, layer=lay_all_role,},
    [267] = {atype=2, srctype=1, targettype=4, width=1.5, length=4, enemy=true, layer=lay_all_role,},
    [268] = {atype=2, srctype=1, targettype=1, angle=90, radius=4, enemy=true, layer=lay_all_role,},
    [269] = {atype=2, srctype=1, targettype=4, width=1.5, length=7.2, enemy=true, layer=lay_all_role,},
    [270] = {atype=2, srctype=1, targettype=4, width=1.5, length=7.2, enemy=true, layer=lay_all_role,},
    [271] = {atype=2, srctype=1, targettype=1, angle=90, radius=7.2, enemy=true, layer=lay_all_role,},
    [272] = {atype=2, srctype=1, targettype=1, angle=360, radius=3, enemy=true, layer=lay_all_role,},
    [273] = {atype=2, srctype=1, targettype=1, angle=360, radius=4, enemy=true, layer=lay_all_role,},
    [274] = {atype=2, srctype=1, targettype=4, width=1.5, length=5, enemy=true, layer=lay_all_role,},
    [275] = {atype=2, srctype=1, targettype=4, width=1.5, length=7.2, enemy=true, layer=lay_all_role,},
    [276] = {atype=2, srctype=1, targettype=4, width=1.5, length=7.2, enemy=true, layer=lay_all_role,},
    [277] = {atype=2, srctype=1, targettype=1, angle=60, radius=7.2, enemy=true, layer=lay_all_role,},
    [278] = {atype=2, srctype=1, targettype=4, width=1.5, length=5, enemy=true, layer=lay_all_role,},
    [279] = {atype=2, srctype=1, targettype=1, angle=180, radius=4, enemy=true, layer=lay_all_role,},
    
    [316] = {atype=2, srctype=1, targettype=4, angle=360, layer=lay_all_role, enemy=true},
    [317] = {atype=2, srctype=1, targettype=4, width=3, layer=lay_all_role, enemy=true, targetcnt=3, sorttype=0,},
    
    [320] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [321] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [322] = {atype=2, srctype=1, targettype=1, angle=360, targetcnt=4, sorttype=0, layer=lay_all_role, enemy=true, arraytype=0},
    
    [325] = {atype=2, srctype=5, targettype=1, radius=2.5, angle=360, enemy=true, layer=lay_all_role, includeself=true, arraytype=0, },
    [326] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, },
    
    [329] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, arraytype=0, },
    [330] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [331] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false, includeself=true, sorttype=4, targetcnt=1,},
    [332] = {atype=2, srctype=1, targettype=6, angle=360, layer=lay_all_role, enemy=false,},
    
    [334] = {atype=2, srctype=1, targettype=4, angle=360, layer=lay_all_role, enemy=true},
    -- [335] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [336] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, radius=3},
    [337] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true,},
    [338] = {atype=2, srctype=1, targettype=1, angle=360, targetcnt=3, layer=lay_all_role, enemy=false, includeself=true},
    [339] = {atype=2, srctype=1, targettype=1, angle=30, layer=lay_all_role, enemy=true},
    
    [341] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [342] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [343] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true },
    [344] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [345] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true,},
    [346] = {atype=2, srctype=1, targettype=4, width=3, layer=lay_all_role, enemy=true, arraytype=0,},
    [347] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [348] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true, arraytype=0, },
    [349] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [350] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [351] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [352] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [353] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [354] = {atype=2, srctype=1, targettype=1, angle=360, targetcnt=3, layer=lay_all_role, enemy=false, includeself=true},
    [355] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [356] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [357] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [358] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [359] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [360] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [361] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [362] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    
    [366] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [367] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [368] = {atype=2, srctype=1, targettype=1, angle=120, targetcnt=3, layer=lay_all_role, enemy=true, arraytype=0,},
    [369] = {atype=2, srctype=1, targettype=2, angle=360, radius=1, layer=lay_all_role, enemy=true},
    [370] = {atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [371] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [372] = {atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [373] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    
    [377] = {atype=2, srctype=1, targettype=1, angle=30, layer=lay_all_role, enemy=true},
    [378] = {atype=2, srctype=1, targettype=1, angle=30, layer=lay_all_role, enemy=true},
    [379] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [380] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [381] = {atype=2, srctype=1, targettype=1, angle=60, layer=lay_all_role, enemy=true},
    [382] = {atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true},
    [383] = {atype=2, srctype=1, targettype=1, angle=90, layer=lay_all_role, enemy=true},
    [384] = { atype=2, srctype=1, targettype=4, layer=lay_all_role, enemy=true, arraytype=0,},
    [385] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [386] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [387] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [388] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [389] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [390] = { atype=2, srctype=3, targettype=1, angle=360, radius=2.5, position=2, layer=lay_all_role, enemy=true},
    [391] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [392] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [393] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [394] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [395] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [396] = { atype=2, srctype=3, targettype=1, angle=360, radius=1, position=2, layer=lay_all_role, enemy=true},
    [397] = { atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [398] = { atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [399] = { atype=2, srctype=1, targettype=1, angle=360, layer=lay_all_role, enemy=true},
    [402] = { atype=2, srctype=1, targettype=4, width=1.5, layer=lay_all_role, enemy=true, arraytype=0,},
    [403] = { atype=2, srctype=1, targettype=4, width=1.5, layer=lay_all_role, enemy=true, arraytype=0,},
    [404] = { atype=2, srctype=1, targettype=1, angle=120, layer=lay_all_role, enemy=true},
    [405] = { atype=2, srctype=3, targettype=1, radius=2, angle=360, position=2, layer=lay_all_role, enemy=true},
    [406] = { atype=2, srctype=3, targettype=1, radius=1, angle=360, position=2, layer=lay_all_role, enemy=true},
    [407] = { atype=2, srctype=3, targettype=1, radius=1, angle=360, position=2, layer=lay_all_role, enemy=true},
}
--[[endregion]]