script.run("logic/ui/trainning_hall/trainning_main.lua")
script.run("logic/ui/trainning_hall/trainning_info.lua")
script.run("logic/ui/trainning_hall/trainning_heroinfo.lua")
script.run("logic/ui/trainning_hall/trainning_uplv.lua")
script.run("logic/ui/trainning_hall/trainning_battle_up.lua")
script.run("logic/ui/trainning_hall/trainning_battle_info.lua")
script.run("logic/ui/trainning_hall/trainning_main_tip.lua")
script.run("logic/ui/trainning_hall/trainning_info_tip.lua")