local GT_NNUM_VALUE = 0
local ENUM_CREATOR = function()
    GT_NNUM_VALUE = GT_NNUM_VALUE + 1
    return GT_NNUM_VALUE
end
Gt_Enum = {
    EMain_Activity	=ENUM_CREATOR()	,--	1主界面-活动
    EMain_SignIn30	=ENUM_CREATOR()	,--	2主界面-30日签到
    EMain_SignIn7	=ENUM_CREATOR()	,--	3主界面-7天乐
    EMain_Task	=ENUM_CREATOR()	,--	4主界面-任务
    EMain_Task_MainTask	=ENUM_CREATOR()	,--	5主界面-任务-主线任务标签
    EMain_Task_DailyTask	=ENUM_CREATOR()	,--	6主界面-任务-支线任务标签
    EMain_Mail	=ENUM_CREATOR()	,--	7主界面-邮件
    EMain_Challenge	=ENUM_CREATOR()	,--	8主界面-挑战
    EMain_Challenge_ActivityLevel	=ENUM_CREATOR()	,--	9主界面-挑战-活动关卡
    EMain_Challenge_ActivityLevel_HighSpeedFighting	=ENUM_CREATOR()	,--	10主界面-挑战-活动关卡-高速阻击
    EMain_Challenge_ActivityLevel_DefendFighting	=ENUM_CREATOR()	,--	11主界面-挑战-活动关卡-保卫战
    EMain_Challenge_ActivityLevel_ClownPlanFighting	=ENUM_CREATOR()	,--	12主界面-挑战-活动关卡-小丑计划 
    EMain_Challenge_ActivityLevel_LimitChallenge	=ENUM_CREATOR()	,--	13主界面-挑战-极限挑战
    EMain_Challenge_ActivityLevel_ExpeditionTrial	=ENUM_CREATOR()	,--	14主界面-挑战-远征试炼
    EMain_Challenge_ActivityLevel_LimitChallenge_start    =ENUM_CREATOR() ,-- 15主界面-挑战-极限挑战-开始按钮
    EMain_Challenge_ActivityLevel_LimitChallenge_goods    =ENUM_CREATOR() ,-- 16主界面-挑战-极限挑战-奖品
    EMain_Challenge_QYZL	=ENUM_CREATOR()	,--	17主界面-挑战-区域占领
    EMain_Challenge_QYZL_Repory	=ENUM_CREATOR()	,--	18主界面-挑战-区域占领-战报按钮
    EMain_Challenge_QYZL_GetReward =ENUM_CREATOR() ,-- 19主界面-挑战-区域占领-领取奖励
    EMain_Challenge_CloneFighting	=ENUM_CREATOR()	,--	20主界面-挑战-克隆站
    EMain_Athletic	=ENUM_CREATOR()	,--	21主界面-竞技 
    EMain_Athletic_Arena	=ENUM_CREATOR()	,--	22主界面-竞技-竞技场 
    EMain_Athletic_Arena_Report	=ENUM_CREATOR()	,--	23主界面-竞技-竞技场-战报 
    EMain_Athletic_Arena_RankAward	=ENUM_CREATOR()	,--	24主界面-竞技-竞技场-排名奖励 
    EMain_Athletic_Arena_ScoreAward	=ENUM_CREATOR()	,--	25主界面-竞技-竞技场-积分奖励 
    EMain_Athletic_WorldBoss	=ENUM_CREATOR()	,--	26主界面-竞技-世界BOSS
    EMain_Athletic_WorldBoss_Start = ENUM_CREATOR() ,-- 27主界面-竞技-世界BOSS-开始按钮
    EMain_Athletic_Fuzion	=ENUM_CREATOR()	,--	28主界面-竞技-大乱斗
    EMain_Athletic_Fuzion_start   =ENUM_CREATOR() ,-- 29主界面-竞技-大乱斗
    EMain_Athletic_3V3	=ENUM_CREATOR()	,--	30主界面-竞技-3V3
    EMain_Athletic_WorldBox	=ENUM_CREATOR()	,--	31主界面-竞技-世界宝箱
    EMain_Hurdle	=ENUM_CREATOR()	,--	32主界面-闯关
    EMain_BattleTeam	=ENUM_CREATOR()	,--	33主界面-战队
    EMain_BattleTeam_Illustrations	=ENUM_CREATOR()	,--	34主界面-战队-图鉴
    EMain_BattleTeam_Illustrations_Main  =ENUM_CREATOR() ,-- 34主界面-战队-图鉴
    EMain_BattleTeam_Illustrations_CCG  =ENUM_CREATOR() ,-- 34主界面-战队-图鉴
    EMain_BattleTeam_Illustrations_SSG  =ENUM_CREATOR() ,-- 34主界面-战队-图鉴
    EMain_BattleTeam_TalentSystem	= ENUM_CREATOR()	,--	35主界面-战队-天赋
    EMain_BattleTeam_TalentSystem_Comprehend	= ENUM_CREATOR()	,--	36主界面-战队-天赋-领悟
    EMain_BattleTeam_TalentSystem_DeepRepair	= ENUM_CREATOR()	,--	37主界面-战队-天赋-深修
    EMain_BattleTeam_TalentSystem_Master	 =ENUM_CREATOR()	,--	38主界面-战队-天赋-精通
    Emain_BattleTeam_Institute = ENUM_CREATOR()	, --39主界面-战队-研究所
    Emain_BattleTeam_Institute_UnLock = ENUM_CREATOR()	, --40主界面-战队-研究所--解锁
    Emain_BattleTeam_trainning = ENUM_CREATOR()	, --41主界面-战队-训练馆
    Emain_BattleTeam_trainning_daren = ENUM_CREATOR()   , --41主界面-战队-训练馆-达人
    Emain_BattleTeam_trainning_info_daren = ENUM_CREATOR()   , --41主界面-战队-训练馆-达人
    Emain_BattleTeam_MaskInfo = ENUM_CREATOR()   , --41主界面-战队-训练馆-达人
    EMain_Heros	=ENUM_CREATOR()	,--	42主界面-角色
    EMain_Enlist	=ENUM_CREATOR()	,--	43主界面-招募 
    EMain_Enlist_1_gold    =ENUM_CREATOR() ,-- 44主界面-招募-一级界面 
    EMain_Enlist_1_crystal    =ENUM_CREATOR() ,-- 45主界面-招募-一级界面 
    EMain_Enlist_2_gold    =ENUM_CREATOR() ,-- 46主界面-招募-二级界面 
    EMain_Enlist_2_crystal    =ENUM_CREATOR() ,-- 47主界面-招募-二级界面 
    EMain_Shop	=ENUM_CREATOR()	,--	48主界面-商店
    EMain_Guild	=ENUM_CREATOR()	,--	49主界面-社团
    EMain_Guild_ST	=ENUM_CREATOR()	,--	50主界面-社团-社团科技
    EMain_Guild_Find_Ls  =ENUM_CREATOR() ,-- 50主界面-社团-寻找力士
    EMain_Guild_ST_Donation	=ENUM_CREATOR()	,--	51主界面-社团-社团科技-捐钱
    EMain_Guild_ST_Donation1 =ENUM_CREATOR() ,-- 52主界面-社团-社团科技-捐钱
    EMain_Guild_ST_Donation2 =ENUM_CREATOR() ,-- 53主界面-社团-社团科技-捐钱
    EMain_Guild_Hall	=ENUM_CREATOR()	,--	54主界面-社团-社团大厅 
    EMain_Guild_Hall_Verify	=ENUM_CREATOR()	,--	55主界面-社团-社团大厅-审核 
    EMain_Guild_Boss	=ENUM_CREATOR()	,--	56主界面-社团-Boss 
    EMain_Friend	=ENUM_CREATOR()	,--	57主界面-好友
    EMain_Friend_List	=ENUM_CREATOR()	,--	58主界面-好友-好友列表
    EMain_Friend_Verify	=ENUM_CREATOR()	,--	59主界面-好友-申请列表
    EMain_FirstRecharge	=ENUM_CREATOR()	,--	60主界面-首冲 
    EMain_LoginAward	=ENUM_CREATOR()	,--	61主界面-登陆 
    EMain_LuckyCat	=ENUM_CREATOR()	,--	62主界面-招财猫
    EMain_LeftCenterMenuButton	=ENUM_CREATOR()	,--	63主界面-左边伸缩按钮 
    EMain_VipGiftPack	=ENUM_CREATOR()	,--	64主界面-VIP礼包
    EMain_Shop_OpenFirstBtn	=ENUM_CREATOR()	,--	65主界面-商店-开启一次按钮
    EMain_Role_ChooseHeroStarToggle	=ENUM_CREATOR()	,--	66主界面-角色-强化按钮(角色养成界面-升星标签)
    EMain_Role_ChooseHeroStarBtn	=ENUM_CREATOR()	,--	67主界面-角色-强化按钮(角色养成界面-升星按钮)
    EMain_Role_ChooseHeroRarityToggle	=ENUM_CREATOR()	,--	68主界面-角色-强化按钮(角色养成界面-升品标签)
    EMain_Role_ChooseHeroRarityBtn	=ENUM_CREATOR()	,--	69主界面-角色-强化按钮(角色养成界面-升品按钮)
    EMain_Role_ChooseHeroRestraintToggle	=ENUM_CREATOR()	,--	70主界面-角色-强化按钮(角色养成界面-克制标签)
    EMain_Role_ChooseHeroRestraintBtn	=ENUM_CREATOR()	,--	71主界面-角色-强化按钮(角色养成界面-克制按钮)
    EMain_Role_ChooseHeroSkillToggle	=ENUM_CREATOR()	,--	72主界面-角色-强化按钮(角色养成界面-克制技能)
    EMain_Role_ChooseHeroEquipStrengthenToggle	=ENUM_CREATOR()	,--	73主界面-角色-装备按钮(角色装备养成界面-装备强化标签)
    EMain_Role_ChooseHeroEquipRarityBtn	=ENUM_CREATOR()	,--	74主界面-角色-装备按钮(角色装备养成界面-装备升品按钮)
    EMain_Role_ChooseHeroEquipStarToggle	=ENUM_CREATOR()	,--	75主界面-角色-装备按钮(角色装备养成界面-装备升星标签)
    EMain_Role_ChooseHeroEquipStarBtn	=ENUM_CREATOR()	,--	76主界面-角色-装备按钮(角色装备养成界面-装备升星按钮)
    EMain_Team_Detail_Equip	=ENUM_CREATOR()	,--	77主界面-阵容-查看详情(阵容强化)-装备
    EMain_Team_Detail_Streagthen	=ENUM_CREATOR()	,--	78主界面-阵容-查看详情(阵容强化)-强化
    EMain_PowerRank  =ENUM_CREATOR() ,-- 79主界面-战力排行
    EMain_Athletic_Arena_ChallengeTimes	=ENUM_CREATOR()	,--	80主界面-竞技-竞技场-当日有可挑战次数
    EMain_Athletic_WorldBoss_Backup = ENUM_CREATOR() ,-- 81主界面-竞技-世界BOSS-助阵按钮
    EMain_Athletic_WorldBox_Start = ENUM_CREATOR() ,-- 82主界面-竞技-世界宝箱-开始按钮
    EMain_Athletic_WorldBox_Backup = ENUM_CREATOR() ,-- 83主界面-竞技-世界宝箱-助阵按钮
    EMain_Bag = ENUM_CREATOR() ,    -- 84 主界面-背包
    EMain_SignIn7_back   =ENUM_CREATOR() ,-- 85主界面-节日7天乐
    EMain_Challenge_HeroTrial	=ENUM_CREATOR()	,--	86主界面-挑战-角色历练
    EMain_BattleTeam_GuardHeart = ENUM_CREATOR()	, --87主界面-战队-守护之心
    EMain_Athletic_WorldBoss_Award = ENUM_CREATOR() ,-- 88主界面-竞技-世界BOSS-奖励按钮
    EMain_Guild_Boss = ENUM_CREATOR() ,-- 89主界面-社团-BOSS
    EMain_Guild_Boss_Award = ENUM_CREATOR() ,-- 90主界面-社团-BOSS-奖励按钮
    EMain_Guild_Boss_Start = ENUM_CREATOR() ,-- 91主界面-社团-BOSS-开始按钮
    EMain_Duel = ENUM_CREATOR() ,-- 92主界面-对决
    EMain_Duel_Chat_Fight = ENUM_CREATOR() ,-- 93主界面-对决-约战
    EMain_Duel_Chat_Fight_Request = ENUM_CREATOR() ,-- 94主界面-对决-约战-请求
    EMain_Duel_Chat_Fight_Award = ENUM_CREATOR() ,-- 95主界面-对决-约战-奖励
    EMain_Duel_Chat_Fight_Award_Fight = ENUM_CREATOR() ,-- 96主界面-对决-约战-奖励-约战
    EMain_Duel_Chat_Fight_Award_Win = ENUM_CREATOR() ,-- 97主界面-对决-约战-奖励-胜利
    EMain_Challenge_VendingMachine	=ENUM_CREATOR()	,--	98主界面-贩卖机
}
GT_NNUM_VALUE = 10000;
Gt_Enum_Wait_Notice =
{
    Success = ENUM_CREATOR(),                               --10000满足条件的通知
    Invalid = ENUM_CREATOR(),                               --10001将再也不做更新
    Player_Levelup = ENUM_CREATOR(),                        --10002玩家升級
    Time = ENUM_CREATOR(),                                  --10003等待时间通知
    Forced = ENUM_CREATOR(),                                --10004强制刷新
    Hero_Add = ENUM_CREATOR(),                              --10005英雄获得
    Hero_LevelUp = ENUM_CREATOR(),                          --10006英雄升级
    Hero_StarUp = ENUM_CREATOR(),                           --10007英雄升星
    Hero_RarityUp = ENUM_CREATOR(),                         --10008英雄升品
    Gold = ENUM_CREATOR(),                                  --10009金币通知
    Item_HeroDebris = ENUM_CREATOR(),                       --10010道具英雄碎片通知
    Item_Talent = ENUM_CREATOR(),                           --10011道具天赋点通知
    Item_Restraint = ENUM_CREATOR(),                        --10012道具克制点通知
    Item_EquipBoxKey = ENUM_CREATOR(),                      --10013道具装备宝箱钥匙通知
    Item_Training_Hall = ENUM_CREATOR(),                    --10014训练馆物品
    Item_RoleRarity = ENUM_CREATOR(),                       --10015英雄升品物品
    Item_EquipRarity = ENUM_CREATOR(),                      --10016装备升品物品
    Item_EquipLevelUp = ENUM_CREATOR(),                     --10017装备升级物品
    Item_EquipStar = ENUM_CREATOR(),                        --10018装备升星物品
    Guild_Wait_Enter = ENUM_CREATOR(),                      --10019等待加入社团
    Guild_Wait_Exit = ENUM_CREATOR(),                       --10020等待退出社团
    Guild_JobChange = ENUM_CREATOR(),                       --10021社团的职位变更
    Guild_IdChange = ENUM_CREATOR(),                        --10022社团id变更(入社，退社)
    Guild_LevelChange = ENUM_CREATOR(),                     --10023社团等级改变
    Institute_Unlock = ENUM_CREATOR(),                      --10024研究院解锁
    Hurdle_StarChange = ENUM_CREATOR(),                     --10025关卡星级变更
    Hurdle_Pass = ENUM_CREATOR(),                           --10026关卡新通关
    Hurdle_GroupAwards = ENUM_CREATOR(),                    --10027关卡章节奖励
    Hurdle_BoxAwards = ENUM_CREATOR(),                      --10028关卡宝箱奖励
    Friend_GetApTimesChange = ENUM_CREATOR(),               --10029好友获取体力次数改变
    Friend_ApplyChange = ENUM_CREATOR(),                    --10030好友请求变化
    Friend_GetApApplyChange = ENUM_CREATOR(),               --10031获取好友赠送体力发生
    Item_RoleLevelUp = ENUM_CREATOR(),                      --10032角色升级物品
    Item_ExchangeType = ENUM_CREATOR(),                     --10033兑换物品
    Guard_Heart = ENUM_CREATOR(),                           --10034守护之心
    Player_FightValue = ENUM_CREATOR(),                     --10035玩家战斗力
    Item_Add = ENUM_CREATOR(),                              --10036获得Item
    Chat_Fight_Request = ENUM_CREATOR(),                    --10037聊天约战申请
    Chat_Fight_Award = ENUM_CREATOR(),                      --10038聊天约战奖励
    Crystal = ENUM_CREATOR(),                               --10039钻石通知
    Vip_Level = ENUM_CREATOR(),                             --10040Vip等级提升
    Item_Mask = ENUM_CREATOR(),                          --10041 面具等级提升
    -- Mask_RarityUp = ENUM_CREATOR(),                          --10041 面具等级提升
    -- Mask_StarUp = ENUM_CREATOR(),                          --10041 面具等级提升
}