

script.run("logic/ui/mmo/main_ui_team_show.lua")
script.run("logic/ui/mmo/main_ui_joystick.lua")
script.run("logic/ui/mmo/main_ui_skill_input.lua")
script.run("logic/ui/mmo/main_ui_player_menu.lua")
script.run("logic/ui/mmo/main_ui_player_menu_callback.lua")
script.run("logic/ui/mmo/main_ui_team.lua")
script.run("logic/ui/mmo/main_ui_option_tip.lua")
script.run("logic/ui/mmo/main_ui_team_can_change.lua")
script.run("logic/ui/mmo/main_ui_progress_bar.lua")
script.run("logic/ui/mmo/main_ui_team_upgrade.lua")
script.run("logic/ui/mmo/main_ui_enemy_hp.lua")
script.run("logic/ui/mmo/main_ui_auto_path_finding.lua")
script.run("logic/ui/mmo/main_ui_player_head.lua")
script.run("logic/ui/mmo/main_ui_team_just_show.lua")
script.run("logic/ui/mmo/main_ui_mmo_pos_exp.lua")
script.run("logic/ui/mmo/main_ui_show_fight_wave.lua")
script.run("logic/ui/mmo/main_ui_chat.lua")
script.run("logic/ui/mmo/main_ui_trigger_operator.lua")
script.run("logic/ui/mmo/skill_show_ui.lua")
script.run("logic/ui/mmo/main_ui_team_both_side.lua")
script.run("logic/ui/mmo/main_ui_captain_reborn_tip.lua")
script.run("logic/ui/mmo/main_ui_fight_monster_guide.lua")

script.run("logic/ui/mmo/mmo_main_ui_component_enum.lua")
script.run("logic/ui/mmo/mmo_main_ui.lua")