-- script.run("logic/data/niudan/niudan.lua")
-- script.run("logic/ui/egg/egg_enum.lua")
script.run("logic/ui/egg/egg_hero_ui.lua")
script.run("logic/ui/egg/egg_hero_sub_ui.lua")
script.run("logic/ui/egg/egg_equip_ui.lua")
script.run("logic/ui/egg/egg_equip_exchange.lua")
script.run("logic/ui/egg/egg_hero_get_ten.lua")
script.run("logic/ui/egg/egg_hero_get_one.lua")
script.run("logic/ui/egg/egg_equip_get_one.lua")
script.run("logic/ui/egg/egg_equip_get_ten.lua")
script.run("logic/ui/egg/egg_hunxia_award_ui.lua")
script.run("logic/ui/egg/egg_get_hero.lua")
script.run("logic/ui/egg/egg_show_3d.lua")
script.run("logic/ui/egg/egg_hero_3d.lua")
script.run("logic/ui/egg/exchange_redcrystal_ui.lua")
script.run("logic/ui/egg/egg_award_show_ui.lua")
script.run("logic/ui/egg/egg_hero_show_ui.lua")
