script.run("logic/message/local_data/mail_data.lua")
script.run("logic/message/local_data/player_data.lua")
script.run("logic/message/local_data/package_local.lua");
script.run("logic/message/local_data/checkin_local.lua");
script.run("logic/message/local_data/level_up_reward_data.lua");
script.run("logic/message/local_data/badges_local.lua");
script.run("logic/message/local_data/store_card_local.lua");
script.run("logic/message/local_data/jtqd_local.lua")
script.run("logic/message/local_data/arena_local.lua")
script.run("logic/message/local_data/chat_local.lua")
script.run("logic/message/local_data/guild_data.lua")
script.run("logic/message/local_data/activity_reward_local.lua")
script.run("logic/message/local_data/shop_local.lua")
script.run("logic/message/local_data/fuzion_local.lua")
script.run("logic/message/local_data/qtjd_local.lua")
script.run("logic/message/local_data/guild_war_local.lua")
